apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  config: |
    [default]
    region = ap-south-1
  syncs3.sh: |
    export AWS_CONFIG_FILE="/root/.aws/config" #change it as per user
    export AWS_ACCESS_KEY_ID=****
    export AWS_SECRET_ACCESS_KEY=*****
    aws s3 sync /var/log/nginx s3://demo-pod-pattern
